- hosts: kubemaster
  become: true
  become_user: root
  tasks:
  - name: start docker
    service: name=docker state=started

  - name: install git
    yum: name=git state=present

  - name: Retrieve AddressBook repository from github
    git: repo=https://github.com/B4SU/add-book.git dest=/tmp/addbook-project
  - name: Deploy AddressBook application
    command: chdir=/tmp/addbook-project kubectl apply -f addressbook-dep.yml
