- hosts: kubemaster
  become: true
  become_user: root
  tasks:
  - name: start docker
    service: name=docker state=started

  - name: install git
    yum: name=git state=present

  - name: Git clone
    git: repo=https://github.com/B4SU/add-book.git dest=/tmp/addbook-project
  - name: Deploy Kubernetes service
    command: chdir=/tmp/addbook-project kubectl apply -f addressbook-dep.yml
